---
title: "EPIET case studies: R guides"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE, 
                      collapse = TRUE, 
                      comment = "#>", 
                      fig.path = "inst/images", 
                      fig.align = "right") 
```


## Overview

This page hosts the R learning materials for the **EPIET Outbreak Investigation module (OIM)**.  

In particular, you will find the R materials for:

   + School dinner foodborne outbreak case study (Copenhagen, Denmark) 
   + Social network analysis practical exercise
   + Unpasteurised milk geospatial analysis and mapping case study (UK)
   + *Campylobacter* water-borne outbreak case study (optional exercise)

Credits go to the original authors of the case studies, as well as the contributors who subsequently adapted the R companion guides (see version history in the guides for a full list of authors and contributors).  The guides are reviewed and updated annually.

These case studies are covered by a Gnu General Public Licence version 3 (GPL-3).  Please read the [licence conditions](https://github.com/EPIET/OutbreakInvestigation/blob/master/LICENSE) before using or distributing this case study.  Additional details on distrubution are also included in the case study guides.


### School dinner case study

To follow the Copenhagen school dinner case study, you will need:

   + [R Copenhagen case study materials](https://epiet.github.io/OutbreakInvestigation/Copenhagen_R_casestudy.zip) (contains data sets, case study guide and R coding template)
   + [R Copenhagen case study guide ](https://epiet.github.io/OutbreakInvestigation/Copenhagen_R_guide.html) (online version)



### Social network analysis practical

To follow the social network analysis practical, you will need:

   + [R Social network analysis practical materials folder](https://epiet.github.io/OutbreakInvestigation/Network_analysis_practical.zip)



### Mapping case study

To follow the UK mapping case study, you will need:

   + [R mapping case study materials](https://epiet.github.io/OutbreakInvestigation/Mapping_R_casestudy.zip) (contains data sets, case study guide and R coding template)
   + [R mapping case study guide ](https://epiet.github.io/OutbreakInvestigation/Mapping_R_guide.html) (online version)


### Campylobacter waterborne outbreak case study

Note: this is an optional exercise, which covers the same analysis strategy as the Copenhagen school dinner case study, but uses an older code base.  We suggest you try this exercise If you have extra time and adapt the code to consolidate your learning.

To follow the *Campylobacter* waterborne outbreak case study, you will need:

   + [R Campylobacter case study materials](https://epiet.github.io/OutbreakInvestigation/Campy_R_casestudy.zip) (contains data sets, case study guide and R coding template)
   + [R Campylobacter case study guide](https://epiet.github.io/OutbreakInvestigation/Campy_R_guide.html) (online version)


## Github repository


### Contributing

The R code for the case study guides and practical materials on this page are hosted on the [Outbreak Investigation Module Github repository](https://github.com/EPIET/OutbreakInvestigation/tree/master/Mapping). Suggestions and updates are welcome; please check out your own branch to commit the updates and then submit a pull request.  Write access to the repository can be provided on request.   


### Comments and suggestions

Comments and suggestions are welcome.  If you have found a bug in the case study code, please raise an issue about it on the [Outbreak Investigation Module GitHub repository issues page](https://github.com/EPIET/OutbreakInvestigation/issues), clearly stating the nature of the problem and providing a reproducible example. You can also use the **issues** page to suggest new features or topics to cover in a future version. 